#!/bin/zsh

#TODO: keep the container running or create the volume.
docker build -t nandhi:latest -f docker/Dockerfile docker
docker run --rm -it -v $(pwd):/nandhi -w /nandhi nandhi:latest bash -c "./aadesh.py install && ./aadesh.py build all"