name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ros2_dev
  TAG_NAME: latest
  REPOSITORY: nandhi

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}