name: ROS 2 CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TAG_NAME: ${{ env.GITHUB_SHA }}
  ROS_CODE_DIR: ${{ env.ROS_CODE_DIR }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      env:
        ROS_CODE_DIR: ${{ env.ROS_CODE_DIR }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my_ros2_image:${{ env.TAG_NAME }}

    - name: Test ROS 2 project
      uses: docker://my_ros2_image:${{ env.TAG_NAME }}
      with:
        entrypoint: ["./ci_cd_action.sh"]
      env:
        ROS_CODE_DIR: ${{ env.ROS_CODE_DIR }}
      volumes:
        - ${{ env.ROS_CODE_DIR }}:/ros2_ws
